#!/usr/bin/env bash

ddev console doctrine:database:drop --force
ddev console doctrine:database:create
ddev console doctrine:migrations:migrate --no-interaction
ddev console hautelook:fixtures:load --quiet